In [52]:
import torch
import numpy as np

In [97]:
data1 = torch.randn(1000,2)
data2 = torch.randn(1000,2)



In [109]:
class Model(torch.nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.fc1 = torch.nn.Linear(2, 32)
        self.fc2 = torch.nn.Linear(32, 32)
        self.fc3 = torch.nn.Linear(32, 1)
        self.relu = torch.nn.ReLU()
        self.batchnorm = torch.nn.BatchNorm1d(32)

    def forward(self, x):
        x = self.relu(self.fc1(x))
        x = self.batchnorm(x)
        x = self.relu(self.fc2(x))
        x = self.batchnorm(x)
        x = self.relu(self.fc3(x))
        return x

In [110]:
model = Model()
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
criterion = torch.nn.BCEWithLogitsLoss()
#criterion = torch.nn.CrossEntropyLoss()

In [111]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [113]:
for epoch in range(5):
    optimizer.zero_grad()

    output1 = model(data1)
    output2 = model(data2)

   # print(out)
    #print(output.grad)
    loss = criterion(output1,torch.ones_like(output1))
    #output1.retain_grad()
   # output1.register_hook(lambda grad: print(grad)) 
   # print(loss.grad)
    loss.backward()
   # print(output1.grad)

    optimizer.step()
    print(loss.item())

0.3516204059123993
0.32816237211227417
0.306540310382843
0.28645455837249756
0.26669904589653015


In [ ]:
def function(x):
    x += 1
    return x

In [ ]:
x = torch.tensor([1.0,2.0, 3.0])


In [ ]:
x

tensor([1., 2., 3.])

In [ ]:
function(x)

tensor([2., 3., 4.])

In [ ]:
x

tensor([2., 3., 4.])